### ISSUE TITLE
(CSS) Code 밑줄 생기는 오류

### ISSUE THREAD

**Issue by Duskafka** [KimKiHyun0206/carte#1]
Code 에 줄이 생기는 오류를 수정하라

**Comment by Duskafka** [comment]
```css
code {
   border : solid 1px black;
}
```
부분이 문제였으며 이것을 삭제했다.
